### ISSUE TITLE
Error in console

### ISSUE THREAD

**Issue by RomeroDiver** [mobinni/material-date-picker#11]
Hi,
I was looking for Material datepickers for Angular, and Yours is one of the best Iv'e seen so far. However, Your datepicker throws error in console:  **TypeError: name.replace is not a function**.
Could You please look into this?
By the way, are You planning to add new functionality to this datepicker - maybe something like disabling dates dynamically(e.g. disable dates from the given array)?
Thanks!

**Comment by RomeroDiver** [comment]
Sorry, didn't see Your comment in the docs

**Comment by mobinni** [comment]
Oh thanks for your comment! I am going to look into this asap. And thanks very much for your praise :).
I will look into adding this functionality.
