### ISSUE TITLE
Error after the last commit

### ISSUE THREAD

**Issue by RomeroDiver** [mobinni/material-date-picker#19]
Hi,
thank You very much for Your fast response - You are doing excellent job!
After Your last commit the datepicker is throwing errors. As far as I can see, this is cause by two new properties that have 2-way databinding - You didn't make them optional, and now if I don't add them I get error. You need to add '?' in the binding --> arrows: '=?', and the same with calendarHeader.
When we are on the subject, it is a very cool new feature(I mean calendarHeader), but I would suggest trying to add localization support - then this porperty won't be necessary.

**Comment by mobinni** [comment]
oh forgot the ? indeed, bit too rapid on developing ^^.
Well technically this adds i18n support, by binding it 2 ways you can fire an event in angular translate to bind the translations and change the scope variable asynchronously, this keeps the codebase clean and allows developers to do as they please

**Comment by mobinni** [comment]
Should be fixed now
