### ISSUE TITLE
Using datepicker in form

### ISSUE THREAD

**Issue by RomeroDiver** [mobinni/material-date-picker#21]
Hi, 
One more suggestion  - if someone would like to use the datepicker in a form, it would be very difficult, cause one cannot set name to the input, or validation attributes - e.g. required. Could You please add maybe name and required attributes so that for example  it would be possible to set if the field is required and check for form validation in submit?
Thanks!

**Comment by mobinni** [comment]
Hey, I'll totally add this in the next round ^^ thanks for your great feedback. Some things you just miss when making it for a specific purpose

**Comment by mobinni** [comment]
Already added name attribute

**Comment by RomeroDiver** [comment]
Maybe You could look at this: http://stackoverflow.com/questions/28045427/angularjs-custom-directive-with-input-element-pass-validator-from-outside .It would be very easy then to add validation attributes I think

**Comment by mobinni** [comment]
Well this could be a future functionality, if you deem it necessary now you can just extract the datepicker and adjust the properties according to your needs.

**Comment by RomeroDiver** [comment]
Well, yes. I just mentioned this as others may need this.

**Comment by mobinni** [comment]
True :D I appreciate your input don't get me wrong!

**Comment by LukaszWiktor** [comment]
I need that! I need to validate a date. The `required` property is one thing but another one is the validity of a manually typed in date. It would be great if material-date-picker had some built-in validation (integrated with angular's validation mechanism) or at least you could pass the standard properties like `required` or`pattern`.

**Comment by mobinni** [comment]
I suggest you fork the repo and add it yourself for the time being.
