### ISSUE TITLE
wrong arrow display

### ISSUE THREAD

**Issue by khalilof** [mobinni/material-date-picker#23]
![shot](https://cloud.githubusercontent.com/assets/1390784/7575121/19e3fc82-f83b-11e4-82b9-22f28d657344.jpg)

**Comment by khalilof** [comment]
removing width from below css classes fixed the issue, 

.header-year
.header-month

khalil

**Comment by mobinni** [comment]
I think this is project specific, because I uploaded the code as is to github pages and it did not have this issue. Nor did it ever in any projects I use it in
