### ISSUE TITLE
How to change date format

### ISSUE THREAD

**Issue by fuzzy31u** [mobinni/material-date-picker#3]
Hello,
I am not sure how to change date format like yyyy-MM-dd after picking date.
Is it possible to configure it?

**Comment by mobinni** [comment]
I was actually working on a format changer for the next revision. As for now to make it easy for you if you go into the datepicker directive and add data-date-format="yyyy-MM-dd" you can actually adjust the datepicker to always have that specific format. http://mgcrea.github.io/angular-strap/#/datepickers. This is the datepicker used.

**Comment by fuzzy31u** [comment]
It works, thank you so much!

**Comment by mobinni** [comment]
No problem, have a great day ;)
