### ISSUE TITLE
Opening Off Page

### ISSUE THREAD

**Issue by pgkehle** [mobinni/material-date-picker#30]
Hi, first, nice plugin!  
I have my input field on the right side of the screen. When the calendar opens, it opens half on/half off the screen because the width is too wide compared to the width of the input field.  Obviously I could move the input field, but there should maybe be a check to ensure it opens on-screen. 

Thanks!

![screenshot 2015-06-01 11 13 48](https://cloud.githubusercontent.com/assets/798015/7916026/4def3fd6-084f-11e5-986e-cb87f7c6a756.png)

**Comment by mobinni** [comment]
what are you trying to use it for, what screen-size?

**Comment by pgkehle** [comment]
This happened to be on an XL screen size, but it is similar for all screen sizes.. 

I don't think I'm doing anything too odd that would cause this to be specific to my setup.   Pretty straightforward:

<code>
div(ng-controller="reportTemplateEditController")
    div(layout="row" layout-margin layout-fill layout-padding)
        h3 {{commandInfo}}

    div(layout="row" layout-margin layout-fill layout-padding)
        div(flex="50")
            md-content(md-theme="altTheme" layout-padding layout="column")
                md-input-container
                    label Name
                    input(ng-model="reportTemplate.description")

        div(flex="25")
            md-content(md-theme="altTheme" layout-padding layout="column")
                md-input-container
                    label Schedule
                md-radio-group(ng-model="reportTemplate.properties.schedule.type")
                    md-radio-button(value="None" class="md-primary") None
                    md-radio-button(value="Once" class="md-primary") One time
                    md-radio-button(value="Daily" class="md-primary") Daily
                    md-radio-button(value="Weekly" class="md-primary") Weekly
                    md-radio-button(value="Monthly" class="md-primary") Monthly
                    md-radio-button(value="Annual" class="md-primary") Annual

        div(flex="25")
            md-input-container
                label Start

                mb-datepicker(element-id='startDate'
                    input-class="testClass"
                    input-name="startDate"
                    arrows="datePicker.arrows"
                    calendar-header="datePicker.header"
                    date="reportTemplate.properties.schedule.startDate"
                    date-format="{{datePicker.format}}")

</code>

(Yes, it's a WIP and I could take out a couple of the layout definitions, etc).

![screenshot 2015-06-01 13 56 19](https://cloud.githubusercontent.com/assets/798015/7919405/0798b76c-0866-11e5-9334-1166fcb7e660.png)

**Comment by mobinni** [comment]
Well the datepicker is not made to be flexible, so it will for instance break off the screen. This is not something I can solve quickly. I'm sorry
