### ISSUE TITLE
how to set default date

### ISSUE THREAD

**Issue by flyher** [mobinni/material-date-picker#31]
hi,
  i set default date:
  $scope.date="2012-09-09"

  and when i open this html,it cannot show the calender about 2012,Sep ‘s,well ,i think you can add an option to decide the date when  it begin,not the date of now.up to user!

**Comment by mobinni** [comment]
good idea, but you should adjust that yourself, for the time being I have my hands full

**Comment by mobinni** [comment]
If I have time I'll definitely implement it

**Comment by flyher** [comment]
Thank you~~~
and 
i have an another problem.
<mb-datepicker element-id='date1'  input-class="testClass" input-name="testName" arrows="arrows"
  calendar-header="header"  date-format="YYYY-MM-DD" ng-model="date"></mb-datepicker>

if i use ng-model to init the default date,it can not be set when i open the html.
Do you have any idea to solve it? 3ks

**Comment by mobinni** [comment]
Because you cannot use ng-model you have to use <  date="date"> date in this case is your scope variable :p then you set that to a value in your controller and done

**Comment by flyher** [comment]
Thank you very much~~~ 
:)
