### ISSUE TITLE
Console.log Left in code

### ISSUE THREAD

**Issue by malammar** [mobinni/material-date-picker#33]
https://github.com/mobinni/material-date-picker/blob/master/app/scripts/mbdatepicker.coffee#L77

Outputs 'undefined' to console every time the app is run.

**Comment by aitorllj93** [comment]
+ 1
In addition, when you set the value in the directive (calendar-header="myvalue"), it doesn't nothing but the console.log

**Comment by RemiAWE** [comment]
:+1: +1 Please fix
