### ISSUE TITLE
Why so much CPU time?

### ISSUE THREAD

**Issue by RichardJECooke** [mobinni/material-date-picker#34]
It seems that all Angular date pickers I try seem to be CPU hogs. This one is a bit better than the official Bootstrap Angular one, but still:
![untitled](https://cloud.githubusercontent.com/assets/5468805/8277264/2a6911ea-18c1-11e5-8016-2edb54136826.png)

Is there any way to avoid this?  It really adds up when you have a few pickers on a few tabs.

**Comment by mobinni** [comment]
I'll try and lower it

**Comment by mobinni** [comment]
Checkout commit 25cb847 for the adjustments you require. Check the changelog for more info.
