### ISSUE TITLE
Next month on June

### ISSUE THREAD

**Issue by danielecammarata** [mobinni/material-date-picker#35]
![1](https://cloud.githubusercontent.com/assets/11610568/8327292/8c40370c-1a67-11e5-9955-811a8db5d015.png)

next month after June gives August

![2](https://cloud.githubusercontent.com/assets/11610568/8327305/9f1e102e-1a67-11e5-9ae0-c6cbeb893f76.png)

going back to June gives a different layout on June

![3](https://cloud.githubusercontent.com/assets/11610568/8327316/b9291004-1a67-11e5-8df1-f41630cbfda5.png)

I think the bug is caused by the first day of June on Monday, I didn't try to solve by my self because I don't have too much knowledge of momentJs functionalities.

**Comment by mobinni** [comment]
Thank you for solving this
