### ISSUE TITLE
Can I make the popup date picker small ?

### ISSUE THREAD

**Issue by alexliubj** [mobinni/material-date-picker#40]
I don't really want it to be so big. Thanks,

**Comment by alexliubj** [comment]
I meant the popup size of date selector.

**Comment by mobinni** [comment]
You can adjust the CSS yourself, the datepicker will work the same, just override the necessary classes in your own css files.

**Comment by alexliubj** [comment]
Can you give me some idea of which part of css I should change for your popup window? I tried and found it was not my css files affect picker.
