### ISSUE TITLE
Using ng-change to run a function when a date is selected

### ISSUE THREAD

**Issue by Aaron-Hartwig** [mobinni/material-date-picker#42]
I'm trying to do some validation on the client when a user selects a date. I put that function in an `ng-change` on the `<mb-datepicker>` element and get the following error `Error: [$compile:ctreq] Controller 'ngModel', required by directive 'ngChange', can't be found!`. Is there a work for doing 'on change' logic?

**Comment by mobinni** [comment]
Currently, if you want to go outside the basic interaction you have to copy the directive locally and add your attributes to the template.

**Comment by Aaron-Hartwig** [comment]
Ok. @mobinni thank you for the quick response :)

**Comment by mobinni** [comment]
No problem mate!
