### ISSUE TITLE
first week missing

### ISSUE THREAD

**Issue by tmx976** [mobinni/material-date-picker#43]
Today, in september and probably for next 3 months, first week is missing when opening the datepicker for the first time, unless a change in motnh or year are requested.

in your `init()` function of the *mbDatePicker* directive you got:
```javascript

firstMonday = moment(moment().date(today.month())).startOf('isoweek');

```

setting date (aka dayOfMonth) with month will end (in case of month 8, 9, 10, 11) to the second week of the month.

I've not tested well on every case, but maybe you could replace your init as

```javascript

firstMonday = moment().date(1).startOf('isoweek');

```

**Comment by mobinni** [comment]
# First day of month
      firstMonday = moment(moment().date(today.month())).startOf('isoweek')
      if(firstMonday.date() == 1) then firstMonday.subtract(1, 'weeks')

it subtracts 7 days if the first day is not 1. Also the online example does show the first week of september. Could you maybe supply screenshots, etc. I'd be happy to look into this further!

**Comment by klode** [comment]
Same problem here, this is a screenshot when the date picker is first opened:

![image](https://cloud.githubusercontent.com/assets/3707306/10055895/a3dc5472-6206-11e5-8126-f2cfcbfa20e2.png)

after changing month or year the problem goes away:

![image](https://cloud.githubusercontent.com/assets/3707306/10055968/12c137b8-6207-11e5-97c8-7c4db4106c60.png)

**Comment by mobinni** [comment]
I will look into this
