### ISSUE TITLE
SVG images not in bower package

### ISSUE THREAD

**Issue by klode** [mobinni/material-date-picker#45]
The SVG images for the arrows are not downloaded with the package (I used bower install material-date-picker)

I noticed that on the master branch the SVGs are in the example/images folder which is not in the bower install. There is no image/ folder neither in app/ nor in build/

The README  suggests the following but I am not sure what it means:
"If you can't find the SVG images, look in the images map of the bower component and copy these to your own images map. I left this as an open option."

**Comment by mobinni** [comment]
Hey as an easy fix I suggest you download the master branch and take the images from there.
