### ISSUE TITLE
Issues building example

### ISSUE THREAD

**Issue by spinningarrow** [mobinni/material-date-picker#5]
There are several issues with the `example` folder: 

1. Executing `bower install` inside `./example` installs libs to `./example/bower_components` but `./example/app/index.html` expects them to be in `./example/app/bower_components`
2. `bower install` fails because of some dependency it can't resolve (`"citylife_styles_and_components"`)
3. `bower.json` doesn't actually list `material-date-picker` as a dependency; the example doesn't work unless installed manually.

**Comment by mobinni** [comment]
I fixed these issues, out of date documentation and removed the faulty example. You can find an example in the docs for now
