### ISSUE TITLE
How could I change the month's name as other language?

### ISSUE THREAD

**Issue by HIKALU-Z** [mobinni/material-date-picker#55]
may i change Dec to 12 ，how can I do it~

**Comment by mobinni** [comment]
I need a little more info to go on. Are you trying to change the default date to dec 12?

**Comment by HIKALU-Z** [comment]
I mean i want to translate the month's name from english to chinese.it can help my customer to read .

**Comment by mobinni** [comment]
You can change the momentJS language to your region's language http://momentjs.com/docs/#/i18n/loading-into-browser/

I don't know if it supports chinese.

If that doesnt work, I would fork this repo and adjust the code to support the chinese months.

**Comment by HIKALU-Z** [comment]
like this
``` 
$scope.month = {
        Jan: '一月',
        Feb: '二月',
       .....
       Dec:'十二月',
    };
```

**Comment by HIKALU-Z** [comment]
thank you very much.
i am a freshman as a front devloper.
thanks for your help~

**Comment by mobinni** [comment]
No problem if you encounter any other problems feel free to email me at mobinni@outlook.com

**Comment by HIKALU-Z** [comment]
woo!
that is so kind of you ,i wish we can be better and better ,and it is lucky to be a firend of you~
