### ISSUE TITLE
Style the selected date in the datepicker

### ISSUE THREAD

**Issue by chrillewoodz** [mobinni/material-date-picker#58]
I thought this was implemented but it doesn't look like it is, how can I alter this line:

    ng-class="::day.class"

To also add a ```selected``` class to the date that is selected? Not sure what the ```::day.class``` does exactly or what condition to apply for the ```selected```class.

I'd appreciate some help :)

**Comment by mobinni** [comment]
Override the css class, css is a waterfall structure so if you redeclare new css for the day class it will be applied.

**Comment by chrillewoodz** [comment]
Well ye I know but the day that is currently selected looks no different from the other days that aren't. So how am I supposed to apply the necessary CSS to just the selected day?

**Comment by mobinni** [comment]
there must be something wrong with your setup, because here: http://mobinni.github.io/material-date-picker/example/ you can clearly see a difference.

**Comment by chrillewoodz** [comment]
A selected day:

```<td ng-click="selectDate(day)" class="noselect ng-binding ng-scope day-item day" ng-class="day.class" ng-repeat="day in week">10</td>```

A non-selected day:

```<td ng-click="selectDate(day)" class="noselect ng-binding ng-scope day-item day" ng-class="day.class" ng-repeat="day in week">11</td>```

How is this clearly a difference? I think you're misunderstanding the issue :)

**Comment by mobinni** [comment]
else if newDate.format(scope.dateFormat) == moment().format(scope.dateFormat)
          day.isToday = true;
          day.isEnabled = true;
          day.class = 'day-item today';

when a day is today, it will get the today class, from the website

```noselect ng-binding ng-scope day-item today```

**Comment by chrillewoodz** [comment]
But I don't want the today class, because today might not be the date that the user has selected. I want the selected date, i.e. the date that the user clicked.

**Comment by mobinni** [comment]
Ohh now I understand what you mean, yes that was not implemented. After a date is selected, the date picker closes. I did not see the need to implement a current_date class. Best would be to fork and implement it. A pull request would be appreciated.

**Comment by chrillewoodz** [comment]
Ye but if you open it again you basically have no idea what date you've previously selected, so it really is a necessity for a datepicker plugin. I tried to implement it but got some readonly assignment error, I'll try to make some viable solution but would be great if you could create a fix since you know more how it works than me and I'm on a limited development time.

**Comment by mobinni** [comment]
Or you could just read the date in the input field? I would love to implement it, but as I said I'm too short on time :/ many projects

**Comment by chrillewoodz** [comment]
Found a really good solution actually, very performance effective. Will fork when I have some time left over :)
