### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by mambax** [mobinni/material-date-picker#60]
I can't see any support for i18n, are you still working this project and if yes is there / will there be any i18n support?

Offtopic: I'm not sure if this is an issue, if not please accept my apology, my thought behind: Maybe others search for this info too, so this is a good place to find information.

**Comment by mobinni** [comment]
You are too polite haha!
As for i18n you can set that up with momentjs. you need to default momentjs to a certain language in your project. Your calendar headers are 2-way databinding so you can switch out the headers you pass to the component on the fly.

```
    <mb-datepicker element-id='date1'
                   input-class="testClass"
                   input-name="testName"
                   arrows="arrows"
                   calendar-header="MYHEADERSSCOPEVAR"
                   date="date"
                   date-format="YYYY-MM-DD"></mb-datepicker>
```
MYHEADERSSCOPEVAR, when this changes so do the values.
