### ISSUE TITLE
Datepicker header is not translating 

### ISSUE THREAD

**Issue by PasanMalith** [mobinni/material-date-picker#65]
I am using this date-picker in Ionic Mobile app and I have linked following lines to translate into French

```
<script type="text/javascript" src="lib/moment/min/moment.min.js"></script>
<script type="text/javascript" src="lib/moment/locale/fr.js"></script>
<script>
    moment.locale('fr');
</script>
```

Button is trnaslating as expected but the headers' month is not translating the month name into French.

You can see screenshot [here](https://s31.postimg.org/xuq6huv7f/image.png)

**Comment by mobinni** [comment]
This is because the month header has a broken implementation detail:

```
      scope.month = $filter('date')(new Date(next_month), 'MMM')
```
you can fork off it and use moment instead. This project is no longer maintained
