### ISSUE TITLE
SVGs not found

### ISSUE THREAD

**Issue by spinningarrow** [mobinni/material-date-picker#8]
When I add it to my project, I get the following 404s:

```
/images/white_arrow_left.svg 404 (Not Found)
/images/white_arrow_right.svg 404 (Not Found)
/images/grey_arrow_left.svg 404 (Not Found)
/images/grey_arrow_right.svg 404 (Not Found)
```

**Comment by mobinni** [comment]
Yes, I will add them now

**Comment by spinningarrow** [comment]
Great, thanks!

**Comment by mobinni** [comment]
SVG's are in the root map under images -> add them to your own project, I deliberately left these out since you can alter the code all you want to show different images, install the bower component and copy the files
